version: '3.8'

services:
  db:
    build:
      context: ./db_docker  # Chemin vers le Dockerfile de la base de données
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5yDT[p9-n5W_5s
      POSTGRES_DB: time_manager_dev  # Nom de la base de données
    ports:
      - "5432:5432"  # Port de la base de données exposé sur l'hôte
      
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  # Port du backend
    environment:
      - PGUSER=postgres
      - PGPASSWORD=5yDT[p9-n5W_5s
      - PGDATABASE=time_manager_dev
      - PGPORT=5432
      - PGHOST=db

    depends_on:
      - db

  
