name: CI/CD
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    environment: CI
    runs-on: ubuntu-latest
 
    steps:
      - name: Vérifier le code
        uses: actions/checkout@v2
 
      - name: Configurer Docker
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
      - name: Construire db
        run: docker build -t andydck/db:latest .

      - name: Construire serveur
        run: docker build -t andydck/backend:latest .
 
      - name: Pousser db
        run: docker push andydck/db:latest

      - name: Pousser serveur
        run: docker push andydck/backend:latest
 
  deploy:
    environment: CI
    runs-on: ubuntu-latest
    needs: build  # Assurez-vous que le job de build soit terminé
 
    steps:
      - name: Vérifier le code
        uses: actions/checkout@v2
 
      - name: Déployer sur le VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${VPS_USER}@${VPS_HOST} << 'EOF'
            docker compose up --build
          EOF
